require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'Appraisals'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.gemfile'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
  TargetRubyVersion: 2.4

Layout/AlignHash:
  EnforcedColonStyle: 'table'

Layout/AlignParameters:
  EnforcedStyle: 'with_fixed_indentation'

Layout/DotPosition:
  EnforcedStyle: 'trailing'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: 'no_space'

Metrics/AbcSize:
  Exclude:
    - 'lib/paperclip/globalize3/attachment.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/paperclip/globalize3/attachment.rb'

Metrics/LineLength:
  Max: 120

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

Style/EmptyElse:
  Exclude:
    - 'lib/paperclip/globalize3/attachment.rb'
