# NOTE: when changing this file, please adapt .travis.yml accordingly

name: Tests

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [master]
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.4.9
          - 2.5.9
          - 2.6.9
        gemfile:
          - rails_4.2_pc_5_3
          - rails_4.2_pc_6_0
          - rails_4.2_pc_6_1
          - rails_5.0_pc_5_3
          - rails_5.0_pc_6_0
          - rails_5.0_pc_6_1
          - rails_5.1_pc_5_3
          - rails_5.1_pc_6_0
          - rails_5.1_pc_6_1
          - rails_5.2_pc_6_1
          - rails_6.0_pc_6_1
        exclude:
          - ruby: 2.4.9
            gemfile: rails_6.0_pc_6_1
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        bundler: 1.17
    - run: bundle exec rake spec
